### ISSUE TITLE
Support Nemo file manager

### ISSUE THREAD

**Issue by slgobinath** [bil-elmoussaoui/nautilus-git#20]
Hi,
First of all, thanks a lot for this great extension and I find it really useful and must to have. I use Linux Mint so converted your extension to Nemo. Just replacing all the `Nautilus` to `Nemo` in the `git.py` did the magic. According to my preliminary testings, it seems to work without any issues in Linux Mint 18.1 with Nemo 3.2.2.
Do you have any idea to support Nemo? If so, I will send a PR to whatever the branch or new repository you prefer.

Thanks again.

**Comment by bilelmoussaoui** [comment]
Hey, 
Thanks for your kind words! Yeah, i would love to support nemo even if i don't use it at all....
I think the best way to deal with that is to keep it in the same directory. Just rename the git.py to nautilus-git & add a nemo-git.py
Sadly, the nautilusPython extension does not allow to import files from either site-packages or whatever you want :p unless you use imp.load_source :/ 

I will figure out something later to avoid replicating the same code for both file manager.
Also, this will require some modifications to the meson build system to make it configurable with an option (see meson_options.txt) with a flag like --fm=nemo or --fm=nautilus in order to avoid installing both versions for users who wants uses one of the two file managers

**Comment by bilelmoussaoui** [comment]
I will create a beta branch where you can push your code right now :+1:

**Comment by slgobinath** [comment]
It's nice to hear that.
I didn't use meson to build the extension. Instead, I manually copy and pasted the `git.py` into
 ```
/usr/share/nemo-python/extensions/
```
`nemo-python` is required for Nemo.
I'll send you the PR soon with the changes I've made so far.

**Comment by bilelmoussaoui** [comment]
Here you go, please submit your patch to the beta branch
the code does not work yet as i've just restructured the code a little bit and nothing is working (missing imports...)
Here's what should be added 
https://github.com/bil-elmoussaoui/nautilus-git/blob/beta/nautilus-git/git.py

And i've already implemented the nemo support on meson , so you won't have to worry about that :)
 https://github.com/bil-elmoussaoui/nautilus-git/blob/beta/meson.build#L26

**Comment by slgobinath** [comment]
I've sent the PR https://github.com/bil-elmoussaoui/nautilus-git/pull/21. As you've mentioned this code doesn't work.

**Comment by bilelmoussaoui** [comment]
Thanks again @slgobinath, i'm going to close this as your PR is already on the beta branch, which helpfully will land on master this weekend/next week!
